// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmgjjxsvliknlbsyoebm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZ2pqeHN2bGlrbmxic3lvZWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Mzk0NTAsImV4cCI6MjA2ODAxNTQ1MH0.YecO2KL11obpsPKiODS7__N4CoBFNttA2IPX6LPlPvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});